### ISSUE TITLE
On some subreddits the app uses a different default sorting

### ISSUE THREAD

**Issue by AlertSubject** [Docile-Alligator/Infinity-For-Reddit#1258]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

Google Play

### Android version

13 - OxygenOS

### Device model

Oneplus9Pro

### First occurred

many months

### Steps to reproduce

Sometimes the app remembers the sort mode I used and then never goes back
I have set the app to not remember my last used sort mode and instead always use "hot" or whatever the default is
for a handful of subreddits (for example leagueofmemes) the app always uses top of month whenever I open the subreddit
Changing the sort mode to hot and then restarting the app also resets it back to top of month

I cant reproduce it 100% of the time but maybe I could give you my backup file as I use the app without a reddit account

### Example post, link, markdown...

r/leagueofmemes

### Expected behaviour

always use the default sort mode

### Current behaviour

A funny mix where it works for most subreddits but a few don't

**Comment by Wladefant** [comment]
Hey @AlertSubject this seems very similar to #736 
If it is, please close this issue and comment there.

**Comment by Docile-Alligator** [comment]
Not remembering sort type is already fixed in v5.4.0.

**Comment by AlertSubject** [comment]
I am on 5.40 and the issue with the above named subreddit still persists
