### ISSUE TITLE
Display message participants name in message list and instead the "Infinity" text

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [Docile-Alligator/Infinity-For-Reddit#492]
When viewing messages in the list only the name of the party is thisplayed that sent the last message.

If entering that message, one could only figure out who they are talking to if they click on the profile picture (in case of a user participant).

But in case of a subreddit's mod, when clicking on the blank profile image one only gets a u/null profile displayed instead of the subreddit's.

I suggest concreticise who are the other party in the message list in some way, same when entered a certsin conversation, display the particular user's or subreddit's name instead of the "Infinity" text.

Could also fix the u/null problem addotionally with displaying the subreddit's profile image instead of a blank one.

**Comment by Docile-Alligator** [comment]
Fixed.

**Comment by IHateTheProgrammingClass** [comment]
@Docile-Alligator Subreddit profile button still does not have an image and still gives a u/null profile.
