### ISSUE TITLE
Images taking forever to load.

### ISSUE THREAD

**Issue by derpyderpaderp** [Docile-Alligator/Infinity-For-Reddit#688]
I've tested this on the version in playstore and fdroid. Since last update images on the front page take forever to load. Some almost take up to 15 second. This never used to be an issue. I will ad this is happening on version 5.1.9 beta. This is happening on both wifi and data. Please if you have a possible solution or may be a issue with the update let me know of a possible fix or update. If you need any information let me know and I'll try and get the information to you ASAP. EDIT: forgot to ad 5.1.8 doesn't have this issue and I tested it to make sure.

**Comment by PotatoesGonnaPotaet** [comment]
I don't know if I should mention this for beta versions, but same issue persists in 5.1.9 beta1

**Comment by Issam28** [comment]
Same problem here. I downgraded to 5.1.9 waiting for this to get fixed in the next release.

**Comment by Alokin-ITA** [comment]
Same issue for me on latest beta, downgraded to 5.1.8 and all went back to normal.
OnePlus 8T
Oxygen OS 11.0.13.13 (Android 11)
Wi-Fi and Cellular
Tested various DNS and the issue persists
Clean install does not resolve the issue

**Comment by Docile-Alligator** [comment]
This is fixed in v5.1.9-beta2.

**Comment by timwhite** [comment]
I'm still having this issue in 5.1.9 from the playstore. I assume that is supposed to already have the fix in it?
