### ISSUE TITLE
Double audio streams in fullscreen with autoplay enabled

### ISSUE THREAD

**Issue by aaronamk** [Docile-Alligator/Infinity-For-Reddit#694]

**Comment by Docile-Alligator** [comment]
I think this is fixed a long time ago? What is your current version?

**Comment by aaronamk** [comment]
> What is your current version?

v5.1.8

**Comment by aaronamk** [comment]
This is still happening for me, now on v5.2.1. Is there more information you need to be able to reproduce?

**Comment by Donkey-Doug** [comment]
Same for me. This issue has been in the app since at least 2 years.

**Comment by aaronamk** [comment]
It seems that the option "Switch to Landscape Orientation in Video Player Automatically" is what causes the issue. When I turn that off it works fine.

**Comment by esnar11** [comment]
> It seems that the option "Switch to Landscape Orientation in Video Player Automatically" is what causes the issue. When I turn that off it works fine.

I have the same issue with and without the switch to landscape orientation automatically so this can't be the only problem.
